# Generated by Django 3.1 on 2023-03-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.CharField(max_length=200),
        ),
    ]
